name: Build OpenTaiko

on: 
  workflow_dispatch:
  
jobs:
  sync:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ${NAME}
          git config --global user.email ${EMAIL}
          git config --global pull.rebase merges
          git pull --unshallow
          git remote add upstream https://github.com/0auBSQ/OpenTaiko.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
        env:
          NAME: ${GITHUB_ACTOR}
          EMAIL: ${GITHUB_ACTOR}@users.noreply.github.com

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore the application
        run: nuget restore $Env:GITHUB_WORKSPACE\TJAPlayer3.sln

      - name: Build the Solution(x64)
        run: MSBuild.exe $Env:GITHUB_WORKSPACE\TJAPlayer3.sln -p:Configuration=Release -p:platform=x64
        timeout-minutes: 5

      - name: Create Archive(x64)
        run: |
          cd $Env:GITHUB_WORKSPACE
          tar -a -cvf OpenTaiko.zip -C Test *
          
      - name: Create Archive(x64) nosong
        run: |
          cd $Env:GITHUB_WORKSPACE
          tar -a -cvf OpenTaiko_nosong.zip --exclude='Songs/*' -C Test *

      - name: Build the Solution(x86)
        run: MSBuild.exe $Env:GITHUB_WORKSPACE\TJAPlayer3.sln -p:Configuration=Release -p:platform=x86
        timeout-minutes: 5

      - name: Create Archive(x86)
        run: |
          cd $Env:GITHUB_WORKSPACE
          tar -a -cvf OpenTaiko-x86.zip -C Test *
          
      - name: Create Archive(x86) nosong
        run: |
          cd $Env:GITHUB_WORKSPACE
          tar -a -cvf OpenTaiko_nosong-x86.zip --exclude='Songs/*' -C Test *

      - name: Get Current Time
        id: time
        shell: pwsh
        run: |
          echo "::set-output name=time::$((Get-Date).addHours(9))"

      - name: Upload Release Asset(x64)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: https://uploads.github.com/repos/totoa553/OpenTaiko/releases/92287065/assets{?name,label}
          file: ./*.zip
          file_glob: true
          overwrite: true
          tag: release
          body: ${{ steps.time.outputs.time }}
